from fpdf import FPDF
import re


# ------------------ TEXT CLEANING ------------------
def clean_text(text: str) -> str:
    if not text:
        return ""

    replacements = {
        '\u2018': "'",
        '\u2019': "'",
        '\u201c': '"',
        '\u201d': '"',
        '\u2013': '-',
        '\u2014': '-',
        '\u2022': '-',
        '\u00b7': '-',
        '\u2026': '...',
    }

    for k, v in replacements.items():
        text = text.replace(k, v)

    text = re.sub(r'(\S{60})', r'\1 ', text)
    text = text.encode("latin-1", errors="replace").decode("latin-1")

    return text.strip()


# ------------------ PDF CLASS ------------------
class SummaryPDF(FPDF):

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(200, 0, 0)

        self.cell(
            0, 10,
            "YouTube Video Summary",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT"
        )

        self.set_text_color(0, 0, 0)
        self.set_draw_color(200, 0, 0)
        self.set_line_width(0.5)

        usable_width = self.w - self.l_margin - self.r_margin
        y = self.get_y()
        self.line(self.l_margin, y, self.l_margin + usable_width, y)

        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)

        self.cell(
            0, 10,
            f"Page {self.page_no()} | Generated by YT Summarizer",
            align="C"
        )

    def section_title(self, title: str):
        self.ln(3)
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(240, 240, 240)

        self.cell(
            0, 8,
            f"  {clean_text(title)}",
            new_x="LMARGIN",
            new_y="NEXT",
            fill=True
        )

        self.ln(2)

    def section_body(self, text: str):
        self.set_font("Helvetica", "", 10)

        usable_width = self.w - self.l_margin - self.r_margin

        self.set_x(self.l_margin)

        self.multi_cell(
            usable_width,
            6,
            clean_text(text),
            align="L"
        )

        self.ln(2)


# ------------------ PDF GENERATION ------------------
def generate_pdf(summary: dict, video_url: str) -> str:

    pdf = SummaryPDF()

    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_left_margin(15)
    pdf.set_right_margin(15)

    pdf.add_page()

    usable_width = pdf.w - pdf.l_margin - pdf.r_margin

    # -------- Source URL --------
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)

    display_url = video_url if len(video_url) < 80 else video_url[:77] + "..."

    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(
        usable_width,
        6,
        f"Source: {clean_text(display_url)}",
        align="L"
    )

    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # -------- Sections --------
    pdf.section_title("Video Topic")
    pdf.section_body(summary.get("title_guess", "N/A"))

    pdf.section_title("Quick Summary")
    pdf.section_body(summary.get("quick_summary", "N/A"))

    pdf.section_title("Key Takeaways")

    for i, point in enumerate(summary.get("key_takeaways", []), 1):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(
            usable_width,
            6,
            clean_text(f"{i}. {point}"),
            align="L"
        )
        pdf.ln(1)

    pdf.section_title("Detailed Summary")
    pdf.section_body(summary.get("detailed_summary", "N/A"))

    pdf.section_title("Keywords")
    keywords = summary.get("keywords", [])
    pdf.section_body(", ".join(keywords))

    # -------- OUTPUT --------
    output_path = f"/tmp/summary_{abs(hash(video_url)) % 100000}.pdf"
    pdf.output(output_path)

    return output_path